version: 2
jobs:
  docker-alpine:
    docker:
      - image: microsoft/dotnet:2.1-sdk-alpine
    steps:
      - checkout
  docker-debian:
    docker:
      - image: microsoft/dotnet:2.1-sdk-stretch
    steps:
      - checkout
  build:
    steps:
      - run:
          name: Dependencies
          command: |
                   cd src
                   dotnet restore
      - run:
          name: Tests
          command: |
                   cd src
                   dotnet test ByteLibLoader.Tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=bin/
workflows:
  version: 2
  test-alpine:
    jobs:
      - docker-alpine
      - build
  test-debian:
    jobs:
      - docker-debian
      - build
