version: 2.1
commands:
  dependencies:
    steps:
      - run:
          name: Dependencies
          command: |
                   cd src
                   dotnet restore
  tests:
    steps:
      - run:
          name: Tests
          command: |
                   cd src
                   dotnet test ByteLibLoader.Tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=bin/
jobs:
  docker-alpine:
    docker:
      - image: microsoft/dotnet:2.1-sdk-alpine
    steps:
      - checkout
      - dependencies
      - tests
  docker-debian:
    docker:
      - image: microsoft/dotnet:2.1-sdk-stretch
    steps:
      - checkout
      - dependencies
      - tests
workflows:
  version: 2.1
  test-alpine:
    jobs:
      - docker-alpine
  test-debian:
    jobs:
      - docker-debian
